wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 64
num_epochs:
  desc: null
  value: 30
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701971903.700094
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 17
      - 23
      - 24
      - 37
      4: 3.8.10
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
    visualize:
      PTB Confusion Matrix:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/confusion_matrix/v1
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: PTB Confusion Matrix_table
                fields: []
      SPH Confusion Matrix:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/confusion_matrix/v1
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: SPH Confusion Matrix_table
                fields: []
